import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import TmuxBar from "@/components/TmuxBar";
import Instructions from "@/components/home/Instructions";
import Launcher from "@/components/Launcher";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "amrit@portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} pb-16 antialiased`}>
        <TmuxBar />
        <Instructions />

        {children}
      </body>
    </html>
  );
}
