import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "amrit@portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} pb-16 antialiased`}>
        {children}
        <div className="fixed bottom-[5px] flex w-full gap-2 bg-green-500 px-2 font-mono text-black">
          <span>[0]</span>
          <Link href={"/"}>0:home</Link>
          <Link href={"https://github.com/amrxt1"}>1:github</Link>
        </div>
      </body>
    </html>
  );
}
